version: '3'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - database
  database:
    image: mysql:8.3.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: library
      MYSQL_USER: root
